<div>
    <p>EMPLOYEE FORM</p>
    <form action="/us8/index/handleform" method="post">
        <label for="employee_name">First Name: 
            <input type="text" name="first_name" id="firstName">
        </label>
        <label for="employee_name">Last Name: 
            <input type="text" name="last_name" id="lastName">
        </label>
        <label for="employee_name">Email: 
            <input type="text" name="email" id="email">
        </label>
        <button type="submit">Add Employee</button>
    </form>
</div>